[package]
name = "park-rusty-roguelike"
version = "1.0.0"
edition = "2021"

[profile.release]
lto = "thin"

[dependencies]
bracket-lib = "~0.8.1"
legion = { version = "=0.3.1", default-features = false, features = ["wasm-bindgen", "codegen"] }
serde = { version = "=1.0.115" }
ron = "=0.7.1"
